name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: [ "bug", "triage" ]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!

- type: input
  id: version
  attributes:
    label: Version
    description: What version of CmdChat are you running?
    placeholder: "0.1.0"
  validations:
    required: true

- type: dropdown
  id: python-version
  attributes:
    label: Python Version
    description: What version of Python are you using?
    options:
    - "3.11"
    - "3.12"
    - "3.13"
    - Other
  validations:
    required: true

- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: What OS are you running on?
    options:
    - Linux
    - macOS
    - Windows
    - Docker
  validations:
    required: true

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: A clear and concise description of the bug
    placeholder: Tell us what you see!
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen?
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce
    description: Steps to reproduce the behavior
    placeholder: |
      1. Start server with '...'
      2. Connect client with '...'
      3. Send message '...'
      4. See error
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output
    render: shell

- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: Add any other context about the problem here
