name: Feature Request
description: Suggest an idea for CmdChat
title: "[Feature]: "
labels: [ "enhancement" ]
body:
- type: markdown
  attributes:
    value: |
      Thanks for suggesting a new feature!

- type: textarea
  id: problem
  attributes:
    label: Problem Description
    description: Is your feature request related to a problem? Please describe.
    placeholder: I'm frustrated when...
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like
    placeholder: I would like to see...
  validations:
    required: true

- type: textarea
  id: alternatives
  attributes:
    label: Alternatives Considered
    description: Describe alternatives you've considered
    placeholder: I also thought about...

- type: dropdown
  id: contribution
  attributes:
    label: Would you like to implement this feature?
    options:
    - "Yes, I would like to implement this"
    - "No, but I can help test it"
    - "No, just suggesting"
  validations:
    required: true

- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here
