name: Dependency Update

on:
  schedule:
    # Run weekly on Monday at 9am UTC
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Update dependencies
        run: |
          pip-compile --upgrade --resolver=backtracking pyproject.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: Update Python dependencies"
          body: "Automated dependency update"
          branch: chore/update-dependencies
          labels: dependencies
